### ISSUE TITLE
Edit icon tool not centered

### ISSUE THREAD

**Issue by Destaq** [Journaly/journaly#523]
#### Perceived Problem

The edit button/comment button when you are trying to correct something on someone's post is not centered, which is frustrating UI-wise. Instead, it *begins* at the halfway mark, not being centered around it.

![image](https://user-images.githubusercontent.com/61620873/111885001-6de1a880-89c5-11eb-9430-b95230a0b419.png)

#### Ideas / Proposed Solution(s)

Using some simple CSS we can fix this. Assuming an `absolute` position:
```css
.icon-class {
  left: 50%;
  transform: translateX(-50%);
}
```

🎉  looks much better!
