### ISSUE TITLE
DEV - Set up Dockerized option for local development

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#568]
#### Description

@JoshuaBelden brought up that suggested that some contributors may prefer to use Docker for local development and kindly offered to take on the work of setting up the necessary configuration and documentation for this with [This Approach Doc](https://github.com/Journaly/journaly/pull/436)

With that approval, let's do it 🙂

**Comment by JoshuaBelden** [comment]
Hey @robin-macpherson! I can take this one!

**Comment by robin-macpherson** [comment]
Awesome! Thanks again for all the work on this @JoshuaBelden 🙏🏼

**Comment by Lanny** [comment]
Awesome to see this getting under way, in additional the the dev QoL benefits I was thinking this might simplify our automated e2e testing in the future (since that involves standing up a fully functional instance in a CI environment). As mentioned in the other ticket, the build process can but a bit tricky so if you run into any issue with that or anything else let us know, happy to help

**Comment by robin-macpherson** [comment]
That's actually great point @Lanny ! I had been thinking about this just the other day as I keep thinking about our Cypress stuff. Hadn't thought of this but it could make that a lot easier.

**Comment by JoshuaBelden** [comment]
Hey all, just an update. I'm still working through containerization. Without changing a bunch of directory structures to support multiple docker files, I'm trying to set up postgres using strictly docker-compose and a docker file to host the web app. I believe this will work but running into several issues getting the web app up while seeding the database and copying and incorporating different .env files from different sub directories.

All solvable I'm sure, I just need to do some more research on the best approach.

**Comment by robin-macpherson** [comment]
Awesome, thanks for the update @JoshuaBelden ! We used to set up PostgreSQL directly from `docker-compose` back when we were Dockerized before which was just something like:
```
services:
  db:
    image: "postgres:11"
    container_name: "journaly_db"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always

volumes:
  db:
```

Good luck and feel free to let us know if we can help!
